### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by kevinsalter**
add missing glob dep

### CODE REVIEW

**Comment by sporto** [comment]
Thanks, but where is this used? What error did you come by?

**Comment by stefanjudis** [comment]
I'm running into this, too.
I followed the instructions made here -> https://www.elm-tutorial.org/en/04-starting/03-webpack-1.html

And when running webpack for the first time this error appears:

```
~/Projects/guardcat | 😪 🤐 👁    master (╯°□°)╯

> npm run dev                                                                                [20:14:31]

> guardcat@1.0.0 dev /Users/stefanjudis/Projects/guardcat
> webpack-dev-server --port 3000

 http://localhost:3000/
webpack result is served from /
content is served from /Users/stefanjudis/Projects/guardcat
Hash: 2aedda5e41f4c1189889
Version: webpack 1.14.0
Time: 1157ms
                                 Asset       Size  Chunks             Chunk Names
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]  
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]  
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]  
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]  
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  
                            index.html  194 bytes          [emitted]  
                                app.js     331 kB       0  [emitted]  app
chunk    {0} app.js (app) 312 kB [rendered]
    [0] multi app 40 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:3000 3.97 kB {0} [built]
    [2] ./~/url/url.js 23.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/url/util.js 314 bytes {0} [built]
    [6] ./~/querystring/index.js 127 bytes {0} [built]
    [7] ./~/querystring/decode.js 2.4 kB {0} [built]
    [8] ./~/querystring/encode.js 2.09 kB {0} [built]
    [9] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [10] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [11] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
   [12] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [13] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [14] ./~/sockjs-client/lib/transport/websocket.js 2.71 kB {0} [built]
   [15] ./~/process/browser.js 5.3 kB {0} [built]
   [16] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [17] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [18] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [19] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [20] ./~/url-parse/index.js 9.92 kB {0} [built]
   [21] ./~/requires-port/index.js 753 bytes {0} [built]
   [22] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
   [23] ./~/querystringify/index.js 1.3 kB {0} [built]
   [24] ./~/debug/browser.js 3.76 kB {0} [built]
   [25] ./~/debug/debug.js 4.1 kB {0} [built]
   [26] ./~/ms/index.js 2.33 kB {0} [built]
   [27] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [28] ./~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
   [29] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [30] ./~/sockjs-client/lib/transport/browser/websocket.js 172 bytes {0} [built]
   [31] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
   [33] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0} [built]
   [34] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
   [35] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [36] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [37] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
   [38] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [built]
   [39] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
   [40] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [41] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [42] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [43] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [44] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
   [45] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
   [46] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
   [47] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [48] ./~/json3/lib/json3.js 43.3 kB {0} [built]
   [49] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [50] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [51] ./~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
   [52] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [53] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [54] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [55] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [56] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [57] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [58] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [59] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [60] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [61] ./~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [62] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [63] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [64] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [65] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [66] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [67] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [68] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [69] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [70] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [71] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [72] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [73] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [74] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [75] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [76] ./src/index.js 449 bytes {0} [built] [1 error]
   [77] ./~/ace-css/css/ace.css 861 bytes {0} [built]
   [78] ./~/css-loader!./~/ace-css/css/ace.css 36.1 kB {0} [built]
   [79] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
   [80] ./~/style-loader/addStyles.js 7.15 kB {0} [built]
   [81] ./~/font-awesome/css/font-awesome.css 888 bytes {0} [built]
   [82] ./~/css-loader!./~/font-awesome/css/font-awesome.css 42 kB {0} [built]
   [83] ./~/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0 82 bytes {0} [built]
   [84] ./~/font-awesome/fonts/fontawesome-webfont.eot 82 bytes {0} [built]
   [85] ./~/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 84 bytes {0} [built]
   [86] ./~/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 83 bytes {0} [built]
   [87] ./~/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 82 bytes {0} [built]
   [88] ./~/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 82 bytes {0} [built]
   [89] ./src/index.html 56 bytes {0} [built]

ERROR in Cannot find module 'glob'
 @ ./src/index.js 9:10-33
webpack: bundle is now VALID.
^C
FAIL: 130
```

**Comment by sporto** [comment]
@kevinsalter 	@stefanjudis Could you paste here you package.json? I suspect some module is using this dependency but not requiring it properly. I will like to see what versions of the npm modules you are using.

**Comment by sporto** [comment]
I'll close this. I don't think that adding the `glob` dependency is the correct way to fix this. I created an issue to track this https://github.com/sporto/elm-tutorial-app/issues/24

**Comment by kevinsalter** [comment]
@sporto @stefanjudis Here's my info.  If there's any other way I could help out, just let me know! 😄 

node `v6.9.1`
npm `3.10.8`

`package.json`
```json
{
  "name": "elm-tutorial-app",
  "version": "1.0.0",
  "description": "",
  "main": "api.js",
  "dependencies": {
    "ace-css": "^1.0.1",
    "css-loader": "^0.23.1",
    "elm-webpack-loader": "^3.0.1",
    "file-loader": "^0.8.5",
    "font-awesome": "^4.6.1",
    "json-server": "^0.9.0",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^1.14.1",
    "webpack": "^1.13.1"
  },
  "devDependencies": {},
  "scripts": {
    "api": "node api.js",
    "build": "webpack",
    "watch": "webpack --watch",
    "dev": "webpack-dev-server --port 3000"
},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sporto/elm-tutorial-app.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/sporto/elm-tutorial-app/issues"
  },
  "homepage": "https://github.com/sporto/elm-tutorial-app#readme"
}
```

And here's the output after running `npm run dev`

```
➜  elm-tutorial-app git:(master) npm run dev                                                                                09:53:10

> elm-tutorial-app@1.0.0 dev /Users/kevinsalter/code/elm-tutorial-app
> webpack-dev-server --port 3000

 http://localhost:3000/
webpack result is served from /
content is served from /Users/kevinsalter/code/elm-tutorial-app
Hash: 945b1edef7d49fd586e4
Version: webpack 1.14.0
Time: 1786ms
                                 Asset       Size  Chunks             Chunk Names
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]
                            index.html  194 bytes          [emitted]
                                app.js     331 kB       0  [emitted]  app
chunk    {0} app.js (app) 312 kB [rendered]
    [0] multi app 40 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:3000 3.97 kB {0} [built]
    [2] ./~/url/url.js 23.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/url/util.js 314 bytes {0} [built]
    [6] ./~/querystring/index.js 127 bytes {0} [built]
    [7] ./~/querystring/decode.js 2.4 kB {0} [built]
    [8] ./~/querystring/encode.js 2.09 kB {0} [built]
    [9] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [10] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [11] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
   [12] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [13] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [14] ./~/sockjs-client/lib/transport/websocket.js 2.71 kB {0} [built]
   [15] ./~/process/browser.js 5.3 kB {0} [built]
   [16] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [17] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [18] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [19] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [20] ./~/url-parse/index.js 9.92 kB {0} [built]
   [21] ./~/requires-port/index.js 753 bytes {0} [built]
   [22] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
   [23] ./~/querystringify/index.js 1.3 kB {0} [built]
   [24] ./~/debug/browser.js 3.76 kB {0} [built]
   [25] ./~/debug/debug.js 4.1 kB {0} [built]
   [26] ./~/ms/index.js 2.33 kB {0} [built]
   [27] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [28] ./~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
   [29] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [30] ./~/sockjs-client/lib/transport/browser/websocket.js 172 bytes {0} [built]
   [31] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
   [33] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0} [built]
   [34] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
   [35] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [36] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [37] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
   [38] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [built]
   [39] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
   [40] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [41] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [42] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [43] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [44] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
   [45] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
   [46] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
   [47] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [48] ./~/json3/lib/json3.js 43.3 kB {0} [built]
   [49] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [50] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [51] ./~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
   [52] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [53] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [54] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [55] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [56] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [57] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [58] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [59] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [60] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [61] ./~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [62] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [63] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [64] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [65] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [66] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [67] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [68] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [69] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [70] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [71] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [72] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [73] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [74] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [75] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [76] ./src/index.js 367 bytes {0} [built] [1 error]
   [77] ./~/ace-css/css/ace.css 861 bytes {0} [built]
   [78] ./~/css-loader!./~/ace-css/css/ace.css 36.1 kB {0} [built]
   [79] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
   [80] ./~/style-loader/addStyles.js 7.15 kB {0} [built]
   [81] ./~/font-awesome/css/font-awesome.css 888 bytes {0} [built]
   [82] ./~/css-loader!./~/font-awesome/css/font-awesome.css 42 kB {0} [built]
   [83] ./~/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0 82 bytes {0} [built]
   [84] ./~/font-awesome/fonts/fontawesome-webfont.eot 82 bytes {0} [built]
   [85] ./~/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 84 bytes {0} [built]
   [86] ./~/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 83 bytes {0} [built]
   [87] ./~/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 82 bytes {0} [built]
   [88] ./~/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 82 bytes {0} [built]
   [89] ./src/index.html 56 bytes {0} [built]

ERROR in Cannot find module 'glob'
 @ ./src/index.js 9:10-31
webpack: bundle is now VALID.
```

**Pull request closed without merging**
